package com.raju.dao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName = "command")
public class Command {
    private String deviceKey; // GUID
    private String commandId; // GUID
    private String commandBody;
    private Integer status;
    private String deviceId;
    private String transactionId;  // GUID
    private Integer onboardCommandId;
    private Integer fileType;
    private Integer sequenceNumber;
    private Boolean binaryDownload;
    private Boolean wifiWakeup;
    private String modifiedBy;
    private Date createdDateTime;
    private Date modifiedDateTime;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getDeviceKey() {
        return deviceKey;
    }

    public void setDeviceKey(String deviceKey) {
        this.deviceKey = deviceKey;
    }

    @DynamoDBAttribute
    public String getCommandId() {
        return commandId;
    }

    public void setCommandId(String commandId) {
        this.commandId = commandId;
    }

    @DynamoDBAttribute
    public String getCommandBody() {
        return commandBody;
    }

    public void setCommandBody(String commandBody) {
        this.commandBody = commandBody;
    }

    @DynamoDBAttribute
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    @DynamoDBAttribute
    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    @DynamoDBAttribute
    public Integer getOnboardCommandId() {
        return onboardCommandId;
    }

    public void setOnboardCommandId(Integer onboardCommandId) {
        this.onboardCommandId = onboardCommandId;
    }

    @DynamoDBAttribute
    public Integer getFileType() {
        return fileType;
    }

    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    @DynamoDBAttribute
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    public void setSequenceNumber(Integer sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    @DynamoDBAttribute
    public Boolean getBinaryDownload() {
        return binaryDownload;
    }

    public void setBinaryDownload(Boolean binaryDownload) {
        this.binaryDownload = binaryDownload;
    }

    @DynamoDBAttribute
    public Boolean getWifiWakeup() {
        return wifiWakeup;
    }

    public void setWifiWakeup(Boolean wifiWakeup) {
        this.wifiWakeup = wifiWakeup;
    }

    @DynamoDBAttribute
    public String getModifiedBy() {
        return modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @DynamoDBAttribute
    public Date getCreatedDateTime() {
        return createdDateTime;
    }

    public void setCreatedDateTime(Date createdDateTime) {
        this.createdDateTime = createdDateTime;
    }

    @DynamoDBAttribute
    public Date getModifiedDateTime() {
        return modifiedDateTime;
    }

    public void setModifiedDateTime(Date modifiedDateTime) {
        this.modifiedDateTime = modifiedDateTime;
    }
}
